created seeding data but they are not seeded yet
akinko0915/EventCalendar pull request #1
Opened 2023-12-02 12:49 UTC by akinko0915

Seeding のデータをつくって、seed.tsも作成してみたのですが、npx prisma db seedをするとエラーが出て上手くseedできませんでした。確認してもらえないでしょうか？
<img width="960" alt="2023-12-02 (1)" src="https://github.com/akinko0915/EventCalendar/assets/114070658/eb6075e4-24be-4d09-bb00-ebd1581496b0">

2023-12-04 01:48 UTC, funobu requested changes
確認しました！

2023-12-04 01:48 UTC, funobu commented on event-calendar/package.json
> +    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts"
```bash
ts-node prisma/seed.ts
```
だけで実行できませんか？CompilerOptionまでは必要ないかと思います。

2023-12-05 02:00 UTC, akinko0915 commented on event-calendar/package.json
> +    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts"
それではじめ一度してみたのですが、できませんでした…

2023-12-05 02:34 UTC, akinko0915 commented on event-calendar/package.json
> +    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts"
データを別のファイルで記述して、seed.tsのファイルの拡張が分からないとなっているのでtsの拡張でのnodeの扱いの設定が上手くいっていないのかなと予測しています。
このようなサイトが見つかりました。なにか思い当たることがあれば教えてください。

<Node.js パッケージ作り方 Pure ESM package と TypeScript 対応 令和最新版>
https://zenn.dev/mr_ozin/articles/6504541653fcb2

<node>
https://nodejs.org/api/packages.html#nodejs-packagejson-field-definitions

2023-12-05 14:03 UTC, akinko0915 commented
seed.tsでseedをできるようになりました。usersとcateogoriesは、seedすることができましたが、titleができません。categoryIdのところでつまずいています。

![image](https://github.com/akinko0915/EventCalendar/assets/114070658/d3f18488-fb1e-4b6b-a6e0-9abaaa12e399)

2023-12-06 05:07 UTC, funobu commented
> seed.tsでseedをできるようになりました。usersとcateogoriesは、seedすることができましたが、titleができません。categoryIdのところでつまずいています。
> 
> ![image](https://private-user-images.githubusercontent.com/114070658/288062507-d3f18488-fb1e-4b6b-a6e0-9abaaa12e399.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mzk0MzQsIm5iZiI6MTcwMTgzOTEzNCwicGF0aCI6Ii8xMTQwNzA2NTgvMjg4MDYyNTA3LWQzZjE4NDg4LWZiMWUtNGI2Yi1hNmUwLTlhYmFhYTEyZTM5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwNTA1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDUyNDM5ZDUxNGRiZDRkYjgwMDZiMzEyN2M5MDdhNDI2NTRmOWE0NjEyNTUxNWNmZTBmNTA3MWY2OWRlYTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q9vIu0bC248Kei-zc2s2zP69R5_hWHshqyB97QPK3Gs)

確認してみたのですが、どうやらTitleのCategoryにユニーク制約がかかっているみたいです。
ユニーク制約がかかっている場合、Titleテーブルの中に同じカテゴリに属するデータを2つ以上増やすことができません。ですので、categoryIdから@uniqueを外した上でマイグレートしたら、解決すると思います。
```ts
model Title{
  id              String @id @default(cuid())
  categoryId      String @unique
  category        Category @relation(fields: [categoryId], references: [id])
  name            String
  form_url        String?
  events          Event[]
}
```

2023-12-06 05:43 UTC, akinko0915 commented
昨日そうしてみたのんですが、できなかったです…。

2023-12-06 08:16 UTC, funobu commented
> 昨日そうしてみたのんですが、できなかったです。同じエラーでした。マイグレーションもしたと思うんですけど、やり方が違ったのかな…
> 
> なにか参考になるサイトを教えていただいてもよろしいでしょうか？

ピンポイントで参考になりそうなサイトはないですね...
ですので、一旦要点を整理しましょう。

まず最初に、`Unique constraint failed on the constraint: `というエラーは、ユニーク制約があるのにも関わらずデータが重複していることを表すエラーです。今回の場合、TitleテーブルのCategoryIdは同じ値が被ることはあり得るので、まず`@unique`を外しましょう。

次に、一旦データベースのデータを削除しましょう。恐らくですが、マイグレーションした後もユニーク制約が残ってしまっているような気がしています。こちらのサイトを参考に、データベースのコンテナのvolumeを削除してみてください。

https://seiyab.hatenablog.com/entry/2020/09/08/185143

次に、event-calendar/prisma/migrations/20231205134313_add_unique_to_category_idを削除しましょう。このファイルが存在するので、再度マイグレーションした際にもユニーク制約がついてしまいます。

最後に、マイグレーションをし、シードデータを入れてみてください。

2023-12-06 08:18 UTC, akinko0915 commented
ご丁寧な説明ありがとうございます。
わかりました。やってみます

2023-12-07 05:27 UTC, akinko0915 commented
volumeが存在しないです。migrationのファイルの削除し、再度migrationしたのですが同じようにユニーク制約でできませんでした。

2023-12-13 08:17 UTC, funobu approved these changes

2023-12-18 05:10 UTC, merged